DOMAIN = "carbon_intensity"

CONFIG_MAIN_REGION = "region"

DATA_CONFIG = "CONFIG"
DATA_RATES_COORDINATOR = "RATES_COORDINATOR"
DATA_RATES = "rates_{}"

EVENT_CURRENT_DAY_RATES = "carbon_intensity_current_day_rates"
EVENT_NEXT_DAY_RATES = "carbon_intensity_next_day_rates"

REFRESH_RATE_IN_MINUTES_RATES = 30
COORDINATOR_REFRESH_IN_SECONDS = 60